In [24]:
from mav_sim.chap2.transforms import *
from IPython import display
from numpy import sin, cos, tan
import numpy as np

array = np.array([[10, 9], [8, 7], [6, 5]])
x = rot_x(np.pi / 3) @ array
z = rot_z(np.pi / 4) @ x
display.display(z[1, 2])

array([[13.57372955, 11.90069694],
       [-0.56840607, -0.82722512],
       [-3.92820323, -3.56217783]])

In [16]:
x_1 = rot_x(np.pi / 6) @ array
y_1 = rot_y(np.pi / 3) @ x_1
z_1 = rot_z(3 * np.pi / 4) @ y_1
display.display(z_1)

array([[ 4.2172567 ,  3.38074039],
       [-9.82334296, -8.72800761],
       [ 9.25833025,  8.20929214]])

In [19]:
from mav_sim.chap3.mav_dynamics import *

phi = np.pi / 3
theta = np.pi / 6
psi = np.pi / 9
pqr = np.array([13, 14, 15])
rot_array = np.array(
    [
        [
            1,
            sin(phi) * tan(theta),
            cos(phi) * tan(theta),
        ],
        [0, cos(phi), -sin(phi)],
        [0, sin(phi) * 1 / cos(theta), cos(phi) * 1 / cos(theta)],
    ]
)
dot = rot_array @ pqr
display.display(dot)

array([24.33012702, -5.99038106, 22.66025404])

In [21]:
import mav_sim.parameters.aerosonde_parameters as MAV

p, q, r = pqr.item(0), pqr.item(1), pqr.item(2)
l, m, n = 4, 5, 6
p_q_r0 = np.array(
    [
        [MAV.gamma1 * p * q - MAV.gamma2 * q * r],
        [MAV.gamma5 * p * r - MAV.gamma6 * (p ** 2 - r ** 2)],
        [MAV.gamma7 * p * q - MAV.gamma1 * q * r],
    ]
)
p_q_r1 = np.array(
    [
        [MAV.gamma3 * l + MAV.gamma4 * n],
        [(1 / MAV.Jy) * m],
        [MAV.gamma4 * l + MAV.gamma8 * n],
    ]
)
rot = p_q_r0 + p_q_r1
display.display(rot)

array([[-135.16542616],
       [ 170.91577093],
       [ -52.35197118]])